In [1]:
print("Python is working!")

Python is working!

In [3]:
import pandas as pd
df = pd.read_csv('customer_shopping_behavior.csv')

ModuleNotFoundError: No module named 'pandas'

In [2]:
df.head()

NameError: name 'df' is not defined

In [4]:
import sys
print(sys.executable)

C:\Users\User\.conda\envs\notebook-env\python.exe

In [8]:
%pip install pandas

Requirement already satisfied: pandas in C:\Users\User\.conda\envs\notebook-env\Lib\site-packages (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\User\.conda\envs\notebook-env\Lib\site-packages (from pandas) (2.5.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\User\.conda\envs\notebook-env\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\User\.conda\envs\notebook-env\Lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in C:\Users\User\.conda\envs\notebook-env\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
df = pd.read_csv('customer_shopping_behavior.csv')

In [2]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [5]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [6]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [50]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

KeyError: 'Category'

In [51]:
df.isnull().sum()

customer_id                0
age                        0
gender                     0
item_purchased             0
category                   0
purchase_amount            0
location                   0
size                       0
color                      0
season                     0
review_rating              0
subscription_status        0
shipping_type              0
discount_applied           0
previous_purchases         0
payment_method             0
frequency_of_purchases     0
age_group                  0
purchase_frequency_days    0
dtype: int64

In [53]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [36]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [15]:
 # create a column age_group

In [54]:
 labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']

 df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)

In [55]:
 df[['age', 'age_group']]. head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [56]:
#  create_column purchase_frequency_days
frequency_mapping = {
       'Fortnightly' : 14,
       'Weekly' : 7,
       'Monthly' : 30,
       'Quarterly' : 90,
       'Bi-Weekly': 14,
       'Annually': 365,
       'Every 3 Months': 90
     }
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [57]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [58]:
df[['promo_code_used','discount_applied']].head(10)

KeyError: "['promo_code_used'] not in index"

In [59]:
(df['discount_applied'] == df['promo_code_used']).all()

KeyError: 'promo_code_used'

In [60]:
df = df.drop('promo_code_used',axis=1)

KeyError: "['promo_code_used'] not found in axis"

In [61]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [50]:
pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.13-cp314-cp314-win_amd64.whl.metadata (5.1 kB)
Collecting sqlalchemy
  Downloading sqlalchemy-2.1.4-cp314-cp314-win_amd64.whl.metadata (9.9 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\User\.conda\envs\notebook-env\Lib\site-packages (from sqlalchemy) (4.16.0)
Downloading psycopg2_binary-2.9.13-cp314-cp314-win_amd64.whl (2.9 MB)
   ---------------------------------------- 0.0/2.9 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.9 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.9 MB 1.2 MB/s eta 0:00:02
   ------- -------------------------------- 0.5/2.9 MB 1.2 MB/s eta 0:00:02
   ------- -------------------------------- 0.5/2.9 MB 1.2 MB/s eta 0:00:02
   ---------- ----------------------------- 0.8/2.9 MB 558.2 kB/s eta 0:00:04
   ---------- ----------------------------- 0.8/2.9 MB 558.2 kB/s eta 0:00:04
   ---------- ----------------------------- 0.8/2.9 MB 558.2 kB/s eta 0:00:04
   ---------- ----------------------------- 0.8/2.9 MB 558.2 kB/s eta 0:00:04
   -------------- ------------------------- 1.0/2.9 MB 467.8 kB/s eta 0:00:04
   -------------- ------------------------- 1.0/2.9 MB 467.8 kB/s eta 0:00:04
   -------------- ------------------------- 1.0/2.9 MB 467.8 kB/s eta 0:00:04
   ------------------ --------------------- 1.3/2.9 MB 431.2 kB/s eta 0:00:04
   ------------------ --------------------- 1.3/2.9 MB 431.2 kB/s eta 0:00:04
   ------------------ --------------------- 1.3/2.9 MB 431.2 kB/s eta 0:00:04
   ------------------ --------------------- 1.3/2.9 MB 431.2 kB/s eta 0:00:04
   --------------------- ------------------ 1.6/2.9 MB 408.8 kB/s eta 0:00:04
   --------------------- ------------------ 1.6/2.9 MB 408.8 kB/s eta 0:00:04
   --------------------- ------------------ 1.6/2.9 MB 408.8 kB/s eta 0:00:04
   ------------------------- -------------- 1.8/2.9 MB 418.6 kB/s eta 0:00:03
   ------------------------- -------------- 1.8/2.9 MB 418.6 kB/s eta 0:00:03
   ------------------------- -------------- 1.8/2.9 MB 418.6 kB/s eta 0:00:03
   ------------------------- -------------- 1.8/2.9 MB 418.6 kB/s eta 0:00:03
   ------------------------- -------------- 1.8/2.9 MB 418.6 kB/s eta 0:00:03
   ----------------------------- ---------- 2.1/2.9 MB 374.3 kB/s eta 0:00:03
   ----------------------------- ---------- 2.1/2.9 MB 374.3 kB/s eta 0:00:03
   ----------------------------- ---------- 2.1/2.9 MB 374.3 kB/s eta 0:00:03
   -------------------------------- ------- 2.4/2.9 MB 376.9 kB/s eta 0:00:02
   -------------------------------- ------- 2.4/2.9 MB 376.9 kB/s eta 0:00:02
   -------------------------------- ------- 2.4/2.9 MB 376.9 kB/s eta 0:00:02
   ------------------------------------ --- 2.6/2.9 MB 377.9 kB/s eta 0:00:01
   ------------------------------------ --- 2.6/2.9 MB 377.9 kB/s eta 0:00:01
   ------------------------------------ --- 2.6/2.9 MB 377.9 kB/s eta 0:00:01
   ---------------------------------------- 2.9/2.9 MB 377.3 kB/s  0:00:06
Downloading sqlalchemy-2.1.4-cp314-cp314-win_amd64.whl (2.4 MB)
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   -------- ------------------------------- 0.5/2.4 MB 302.1 kB/s eta 0:00:07
   -------- ------------------------------- 0.5/2.4 MB 302.1 kB/s eta 0:00:07
   -------- ------------------------------- 0.5/2.4 MB 302.1 kB/s eta 0:00:07
   -------- ------------------------------- 0.5/2.4 MB 302.1 kB/s eta 0:00:07
   ------------ --------------------------- 0.8/2.4 MB 311.1 kB/s eta 0:00:06
   ------------ --------------------------- 0.8/2.4 MB 311.1 kB/s eta 0:00:06
   ------------ --------------------------- 0.8/2.4 MB 311.1 kB/s eta 0:00:06
   ------------ --------------------------- 0.8/2.4 MB 311.1 kB/s eta 0:00:06
   ----------------- ---------------------- 1.0/2.4 MB 299.8 kB/s eta 0:00:05
   ----------------- ---------------------- 1.0/2.4 MB 299.8 kB/s eta 0:00:05
   ----------------- ---------------------- 1.0/2.4 MB 299.8 kB/s eta 0:00:05
   ----------------- ---------------------- 1.0/2.4 MB 299.8 kB/s eta 0:00:05
   ----------------- ---------------------- 1.0/2.4 MB 299.8 kB/s eta 0:00:05
   --------------------- ------------------ 1.3/2.4 MB 298.7 kB/s eta 0:00:04
   --------------------- ------------------ 1.3/2.4 MB 298.7 kB/s eta 0:00:04
   ------------------------- -------------- 1.6/2.4 MB 331.5 kB/s eta 0:00:03
   ------------------------- -------------- 1.6/2.4 MB 331.5 kB/s eta 0:00:03
   ------------------------------ --------- 1.8/2.4 MB 354.4 kB/s eta 0:00:02
   ------------------------------ --------- 1.8/2.4 MB 354.4 kB/s eta 0:00:02
   ------------------------------ --------- 1.8/2.4 MB 354.4 kB/s eta 0:00:02
   ------------------------------ --------- 1.8/2.4 MB 354.4 kB/s eta 0:00:02
   ------------------------------ --------- 1.8/2.4 MB 354.4 kB/s eta 0:00:02
   ---------------------------------- ----- 2.1/2.4 MB 333.4 kB/s eta 0:00:02
   ---------------------------------- ----- 2.1/2.4 MB 333.4 kB/s eta 0:00:02
   ---------------------------------- ----- 2.1/2.4 MB 333.4 kB/s eta 0:00:02
   ---------------------------------- ----- 2.1/2.4 MB 333.4 kB/s eta 0:00:02
   -------------------------------------- - 2.4/2.4 MB 327.9 kB/s eta 0:00:01
   ---------------------------------------- 2.4/2.4 MB 330.8 kB/s  0:00:07
Installing collected packages: sqlalchemy, psycopg2-binary

   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [psycopg2-binary]
   -------------------- ------------------- 1/2 [psycopg2-binary]
   -------------------- ------------------- 1/2 [psycopg2-binary]
   ---------------------------------------- 2/2 [psycopg2-binary]

Successfully installed psycopg2-binary-2.9.13 sqlalchemy-2.1.4
Note: you may need to restart the kernel to use updated packages.

In [1]:
from sqlalchemy import create_engine

In [62]:
username = "postgres"

In [63]:
password = "Nakul8108"

In [64]:
host = "localhost"

In [65]:
port ="5432"

In [66]:
database ="Customer_behavior"

In [67]:
connection_string = f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"

In [68]:
engine = create_engine(connection_string)

In [69]:
with engine.connect() as connection:
    print("Connection successful!")

Connection successful!

In [70]:
table_name = "customer"

In [71]:
df.to_sql(table_name, engine, if_exists="replace", index=False)

900

In [19]:
import pandas as pd

In [72]:
df = pd.read_csv('customer_shopping_behavior.csv')

In [73]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [52]:
df.isnull().sum()

customer_id                0
age                        0
gender                     0
item_purchased             0
category                   0
purchase_amount            0
location                   0
size                       0
color                      0
season                     0
review_rating              0
subscription_status        0
shipping_type              0
discount_applied           0
previous_purchases         0
payment_method             0
frequency_of_purchases     0
age_group                  0
purchase_frequency_days    0
dtype: int64

Customer ID               True
Age                       True
Gender                    True
Item Purchased            True
Category                  True
Purchase Amount (USD)     True
Location                  True
Size                      True
Color                     True
Season                    True
Review Rating             True
Subscription Status       True
Shipping Type             True
Discount Applied          True
Promo Code Used           True
Previous Purchases        True
Payment Method            True
Frequency of Purchases    True
dtype: bool

In [76]:
df.shape

(3900, 18)

In [77]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [78]:
display(df)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

In [79]:
df.to_sql(table_name, engine, if_exists="replace", index=False)

900

In [80]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [81]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [82]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [83]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [84]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [85]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [86]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [87]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [88]:
 labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']

 df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)

In [89]:
 df[['age', 'age_group']]. head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [90]:
#  create_column purchase_frequency_days
frequency_mapping = {
       'Fortnightly' : 14,
       'Weekly' : 7,
       'Monthly' : 30,
       'Quarterly' : 90,
       'Bi-Weekly': 14,
       'Annually': 365,
       'Every 3 Months': 90
     }
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [91]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [92]:
df[['promo_code_used','discount_applied']].head(10)

  promo_code_used discount_applied
0             Yes              Yes
1             Yes              Yes
2             Yes              Yes
3             Yes              Yes
4             Yes              Yes
5             Yes              Yes
6             Yes              Yes
7             Yes              Yes
8             Yes              Yes
9             Yes              Yes

In [93]:
df = df.drop('promo_code_used',axis=1)

In [94]:
df.to_sql(table_name, engine, if_exists="replace", index=False)

900

In [95]:
df.shape

(3900, 19)